version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Cleaning node_modules directory
      - rm -rf app/node_modules
      - echo Installing yarn and libs
      - npm install -g yarn
      - cd app/ && yarn install
      - zip -r sqs.zip src/sqs index.js node_modules
      - aws s3 cp sqs.zip s3://bd-no-serverless/sqs.zip
  build:
    commands:
      - echo "Sqs function build complete"
cache:
  files:
    - sqs.zip
  paths:
    - node_modules
