version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Cleaning node_modules directory
      - rm -rf app/node_modules
      - echo Installing yarn and libs
      - npm install -g yarn
      - cd app/ && yarn install
      - ls
      - yarn build
  build:
    commands:
      - zip -r sqs.zip build/ node_modules package.json
      - aws s3 cp sqs.zip s3://bd-no-serverless/sqs.zip
      - aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key sqs.zip
  post_build:
    commands:
      - echo "Sqs function build complete"
cache:
  files:
    - sqs.zip
  paths:
    - node_modules
