version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Cleaning node_modules directory
      - rm -rf app/node_modules
      - echo Installing yarn and libs
      - npm install -g yarn
      - cd app/ && yarn install
      - yarn build
  build:
    commands:
      - zip -r api.zip build/ node_modules package.json
      - aws s3 cp api.zip s3://bd-no-serverless/api.zip
      - aws lambda update-function-code --function-name $LAMBDA_API_FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key api.zip
  post_build:
    commands:
      - echo "API function build complete"
cache:
  files:
    - api.zip
  paths:
    - node_modules
