version: 0.2
run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Cleaning node_modules directory
      - rm -rf app/node_modules
      - echo Installing yarn and libs
      - npm install -g yarn typescript
      - cd app/ && yarn install
      - yarn tsc
      - zip -r api.zip .build/api node_modules
      - aws s3 cp api.zip s3://bd-no-serverless/api.zip
  build:
    commands:
      - echo "API function build complete"
cache:
  files:
    - api.zip
  paths:
    - node_modules
